### ISSUE TITLE
关于 wx:key 有个值得注意的点，再补充一下 wx:for 相关

### ISSUE THREAD

**Issue by aweiu** [espkg/mina2vue#13]
小程序的 block 上可以写 wx:key，而转成对应 vue 的 template 后，template 上是不支持写 key 的。
这个感觉应该得给 block 下面的所有根子节点上都加一个类似 `wx:key + index` 的值来解决

**Comment by aweiu** [comment]
微信的 wx:for 还支持字符串遍历，类似这样的语法 `wx:for="{{list1}}{{list2}}123"` ，转换成 vue 应该是
`v-for="(item, index) of (list + list + '123')"`。当然，还有 item 和 index 的名字也得支持自定义。

另外，推荐使用 https://github.com/posthtml/posthtml 来写吧，我现在就用它做的，api 很简单很方便！加油！

**Comment by Maopy** [comment]
> 微信的 wx:for 还支持字符串遍历，类似这样的语法 `wx:for="{{list1}}{{list2}}123"` ，转换成 vue 应该是
> `v-for="(item, index) of (list + list + '123')"`。当然，还有 item 和 index 的名字也得支持自定义。
> 
> 另外，推荐使用 https://github.com/posthtml/posthtml 来写吧，我现在就用它做的，api 很简单很方便！加油！

好的，我看下这个项目，感谢！
